### ISSUE TITLE
Disponibilizar compatibilidade da versão 2 para projetos que ainda usam versão mais antiga da lib

### ISSUE THREAD

**Issue by edimarlnx** [tecsinapse/tecsinapse-data-io#18]
Disponibilizar classes de compatibilidade da versão 2 para projetos que ainda usam versão mais antiga da lib.

**Comment by filipenevola** [comment]
Olá @edimarlnx , eu fui utilizar essa nova versão mas tive problemas devido a muitas mudanças na API e também falta de documentação de como usar a parte do Exporter.

Por exemplo, sempre utilizei o TableCell construindo passando uma String (que é o tipo mais comum de uma exportação) e agora nessa versão eu não consegui fazer isso, por fim, desistir de migrar para essa versão pois eu nem estava conseguindo utilizar pois força usar um Object (o que é estranho), normalmente APIs que querem ser mais genéricas usam Generics ao invés de Object.

Acho que podemos refletir melhor nessas mudanças e criar formas mais fáceis de uso, que deve ser o principal foco.

Aguardo suas respostas dos pontos acima para continuarmos pensando nesse sentido.

Abraços

**Comment by edimarlnx** [comment]
@filipenevola sobre as ponderações são válidas sim. Vou tentar responder (em outra ordem, mas a todas)

**Sobre quebrar projetos já em uso**: Como já discutimos em outra oportunidade, vou trazer as classes que permitem compatibilidade do projeto a versões antigas. Estas classes são exclusivas para manter compatibilidade, mas internamente já fazem chamadas a novas funcionalidades e correções feitas nesta versão. Com isto, realmente não há problema em manter. Só vou ter o cuidado de deixar comentado qual a forma ideal de chamar (@Deprecated).

**Sobre o uso do TableCell**: alterei para objeto, mas sua observação é pertinente. O objetivo aqui era dentro do próprio código identificar o tipo de dado que está recebendo e exportar com o tipo ideal do excel. Mas talvez faça mais sentido mesmo ter métodos com tipos definidos, no caso seriam: Number (BigDecilmal, Interger, ,,,,), Date (Date, hora, Date e hora (*1)) e String. Esta funcionalidade de armazenar os dados nativos no excel, permite que se ordene campo com Data e Valores numéricos como se é esperado.

*1 - Como estamos compilado em java 7, ou usamos o joda ou usamos date. Usando date como eu optei por fazer, acabamos perdendo a separação de Date, Time e DateTime. Dado que logo logo já estaremos entrando no java 9, estava pensando em definirmos que esta lib usa java 8. Assim teríamos um bom ganho nestas separações por tipo nativo do java 8 (LocalDate, LocalDateTime e LocalTime).

**Comment by filipenevola** [comment]
@edimarlnx o ideal seria não depreciar, apenas chamar a nova dentro da antiga, se depreciar vai gerar Warnings e a galera vai precisar alterar da mesma forma.

E quanto ao Object eu não falei em ter métodos para cada tipo, até poderia ter mas não foi esse o meu ponto, meu ponto foi: se quer representar N tipos use Generics ao invés de Object.

Acho ruim suportar apenas Java 8, a maioria das pessoas ainda está usando Java 6 ou 7 e muitas empresas ainda usam Java 3, 4 e 5 então quanto maior for a versão obrigatória menos pessoas vão utilizar nossa API. A menos que tenhamos um ganho real que valha muito a pena eu deixaria no 7 mesmo, que já é uma versão bem alta.

E não entendi essa frase: "Assim teríamos um bom ganho " qual ganho de usar a JSR310 ao invés do Joda? Inclusive eu prefiro o Joda ;) Foi o Stephen que projetou boa parte de ambos, ele até acha que a JSR310 tem uma arquitetura melhor mas eu acho que a usabilidade do Joda é bem melhor por não se preocupar com casos muito extremos como a JSR teve que se preocupar. Enfim, sempre bom ponderar ganhos reais quando estamos falando de troca de tecnologias, versões, etc pois o que importa é o resultado queremos e não os detalhes do que usamos para chegar nesse resultado.

**Comment by edimarlnx** [comment]
@filipenevola vou providenciar alguns vídeos falando sobre a migração, acredito que será mais intuitivo. Neste também vou explicar o motivo de algumas refatorações serem necessárias, principalmente visando um problemas que sempre tivemos se tratando de xlsx no qual as datas são importadas de forma incorreta em alguns casos.
